# Lab 1.01 - Australian Athletes (ais)

In the Python cell below this one, paste all the imports you need for data analysis from the code examples (Numpy, Pandas, etc.).

In [49]:
# Importing the necessary packages
import numpy as np                                  # "Scientific computing"
import scipy.stats as stats                         # Statistical tests

import pandas as pd                                 # Data Frame
from pandas.api.types import CategoricalDtype

import matplotlib.pyplot as plt                     # Basic visualisation
from statsmodels.graphics.mosaicplot import mosaic  # Mosaic diagram
import seaborn as sns                               # Advanced data visualisation

Declare a variable `ais` and use it to import the dataset from the CSV-file `ais.csv` in [the directory `data/`](https://github.com/HoGentTIN/dsai-en-labs/tree/main/data) of the [Github repository](https://github.com/HoGentTIN/dsai-en-labs/) for the lab assignments. You can import a dataset with a URL pointing to the raw contents of the CSV-file in the Github repository (see the code example!).

This dataset contains 202 observations of Australian athletes with a variety of blood values. You can find the codebook (i.e., the explanation of what each variable/column in the dataset means) in [data/ais.md](https://github.com/HoGentTIN/dsai-en-labs/blob/main/data/ais.md). Show the first few observations of this sample.

In [50]:
ais = pd.read_csv("../data/ais.csv")  # Load the data
ais.head()  # Show the first 5 rows of the data frame

,id,rcc,wcc,hc,hg,ferr,bmi,ssf,pcBfat,lbm,ht,wt,sex,sport
0,1,3.96,7.5,37.5,12.3,60,20.56,109.1,19.75,63.32,195.9,78.9,f,B_Ball
1,2,4.41,8.3,38.2,12.7,68,20.67,102.8,21.30,58.55,189.7,74.4,f,B_Ball
2,3,4.14,5.0,36.4,11.6,21,21.86,104.6,19.88,55.36,177.8,69.1,f,B_Ball
3,4,4.11,5.3,37.3,12.6,69,21.88,126.4,23.66,57.18,185.0,74.9,f,B_Ball
4,5,4.45,6.8,41.5,14.0,29,18.96,80.3,17.64,53.20,184.6,64.6,f,B_Ball

Get general information about this dataset:

- How many rows and columns does the dataset have?
- Show general information about each variable, specifically the number of empty fields and the type of each variable (e.g., int64, float64, object)
- How many columns of each type are there?
- What is the measurement level (nominal, ordinal, interval, ratio) of each variable?

In [32]:
print(len(ais))  # Show the number of rows in the data frame
print(len(ais.columns))  # Show the number of columns in the data frame
print(ais.shape)  # Show the number of rows and columns in the data frame

print(ais.info())  # Show the data types of each column and the number of non-null values

print(ais.dtypes.value_counts())  # Show the data types of each column

# print(ais.describe()) # Show summary statistics for the numerical columns

# print(ais.describe(include=["str", "object"]))  # Show summary statistics for the categorical columns

202
13
(202, 13)
<class 'pandas.DataFrame'>
RangeIndex: 202 entries, 1 to 202
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   rcc     202 non-null    float64
 1   wcc     202 non-null    float64
 2   hc      202 non-null    float64
 3   hg      202 non-null    float64
 4   ferr    202 non-null    int64
 5   bmi     202 non-null    float64
 6   ssf     202 non-null    float64
 7   pcBfat  202 non-null    float64
 8   lbm     202 non-null    float64
 9   ht      202 non-null    float64
 10  wt      202 non-null    float64
 11  sex     202 non-null    str
 12  sport   202 non-null    str
dtypes: float64(10), int64(1), str(2)
memory usage: 20.6 KB
None
float64    10
str         2
int64       1
Name: count, dtype: int64

The column "id" is not an actual variable, but an index. Mark it as such.

In [26]:
ais = ais.set_index("id")  # Set the "ID" column as the index of the data frame
ais.head()  # Show the first 5 rows of the data frame

,rcc,wcc,hc,hg,ferr,bmi,ssf,pcBfat,lbm,ht,wt,sex,sport
id,,,,,,,,,,,,,
1,3.96,7.5,37.5,12.3,60,20.56,109.1,19.75,63.32,195.9,78.9,f,B_Ball
2,4.41,8.3,38.2,12.7,68,20.67,102.8,21.30,58.55,189.7,74.4,f,B_Ball
3,4.14,5.0,36.4,11.6,21,21.86,104.6,19.88,55.36,177.8,69.1,f,B_Ball
4,4.11,5.3,37.3,12.6,69,21.88,126.4,23.66,57.18,185.0,74.9,f,B_Ball
5,4.45,6.8,41.5,14.0,29,18.96,80.3,17.64,53.20,184.6,64.6,f,B_Ball

The variables that are now considered "object" are qualitative variables. Change the type of each of these variables to "category". For ordinal variables, also define a type and impose an order. Verify that the conversion was successful by requesting info about the types again.

In [41]:
ais.sex = ais.sex.astype("category")  # Convert the "sex" column to a categorical data type
ais.head()  # Show the first 5 rows of the data frame
ais.sport = ais.sport.astype("category")  # Convert the "sport" column to a categorical data type
ais.head()  # Show the first 5 rows of the data frame

print(ais.sex.describe()) # Show summary statistics for the "sex" column

print(ais.sport.describe()) # Show summary statistics for the "sport" column

count     202
unique      2
top         m
freq      102
Name: sex, dtype: object
count     202
unique     10
top       Row
freq       37
Name: sport, dtype: object

Describe the columns `ferr`, `bmi`, `sex` and `sport` and the unique values in each of these columns. Do you recognize the characteristics of qualitative and quantitative variables in the result?

Select following elements from the dataset:

- the second row (ids = 2)
- rows 4 to 6 (ids = 5 to 7)
- Columns 6 to 8 (`ferr`, `bmi`, `ssf`)
- the variable `pcBfat` (by name!). There are multiple ways to retrieve this!
- all observations for the sport "Netball"
- just the variable `wt` of the observations for "Netball"
- which sports are played by athletes with a BMI higher than 26? Also, provide a list of the unique values and a frequency table of how often each sport occurs.

In [52]:
# the second row (ids = 2)
print(ais.iloc[1])  # Show the second row of the data frame (index starts at 0)
# rows 4 to 6 (ids = 5 to 7)
print(ais.iloc[4:7])  # Show rows 4 to 6 of the data frame (index starts at 0)
# Columns 6 to 8 (`ferr`, `bmi`, `ssf`)
print(ais[['ferr','bmi','ssf']])  
# the variable `pcBfat` (by name!). There are multiple ways to retrieve this!
print(ais['pcBfat'])  # Show the `pcBfat` column of the data frame
print(ais.pcBfat)  # Show the `pcBfat` column of the data frame
print(ais.iloc[:, 10])  # Show the `pcBfat` column of the data frame (index starts at 0)
# all observations for the sport "Netball"
print(ais[ais.sport == "Netball"])  # Show all rows where the sport is "Netball"
# just the variable `wt` of the observations for "Netball"
print(ais[ais.sport == "Netball"].wt)  # Show the `wt` column for all rows where the sport is "Netball"
# which sports are played by athletes with a BMI higher than 26? Also, provide a list of the unique values and a frequency table of how often each sport occurs.
print(ais[ais.bmi > 26].sport.unique())  # Show the unique sports played by athletes with a BMI higher than 26
print(ais[ais.bmi > 26].sport.value_counts())  # Show the frequency of each sport played by athletes with a BMI higher than 26

id             2
rcc         4.41
wcc          8.3
hc          38.2
hg          12.7
ferr          68
bmi        20.67
ssf        102.8
pcBfat      21.3
lbm        58.55
ht         189.7
wt          74.4
sex            f
sport     B_Ball
Name: 1, dtype: object
   id   rcc  wcc    hc    hg  ferr    bmi   ssf  pcBfat    lbm     ht    wt  \
4   5  4.45  6.8  41.5  14.0    29  18.96  80.3   17.64  53.20  184.6  64.6
5   6  4.10  4.4  37.4  12.5    42  21.04  75.2   15.58  53.77  174.0  63.7
6   7  4.31  5.3  39.6  12.8    73  21.69  87.2   19.99  60.17  186.2  75.2

  sex   sport
4   f  B_Ball
5   f  B_Ball
6   f  B_Ball
     ferr    bmi    ssf
0      60  20.56  109.1
1      68  20.67  102.8
2      21  21.86  104.6
3      69  21.88  126.4
4      29  18.96   80.3
..    ...    ...    ...
197    90  27.56   67.2
198    38  23.76   56.5
199   122  22.01   47.6
200   233  22.34   60.4
201    32  21.07   34.9

[202 rows x 3 columns]
0      19.75
1      21.30
2      19.88
3      23.66
4      17.64
       ...
197    11.79
198    10.05
199     8.51
200    11.50
201     6.26
Name: pcBfat, Length: 202, dtype: float64
0      19.75
1      21.30
2      19.88
3      23.66
4      17.64
       ...
197    11.79
198    10.05
199     8.51
200    11.50
201     6.26
Name: pcBfat, Length: 202, dtype: float64
0      195.9
1      189.7
2      177.8
3      185.0
4      184.6
       ...
197    183.9
198    183.5
199    183.1
200    178.4
201    190.8
Name: ht, Length: 202, dtype: float64
    id   rcc   wcc    hc    hg  ferr    bmi    ssf  pcBfat    lbm     ht  \
35  36  4.56  13.3  42.2  13.6    20  19.16   49.0   11.29  53.14  176.8
36  37  4.15   6.0  38.0  12.7    59  21.15  110.2   25.26  47.09  172.6
37  38  4.16   7.6  37.5  12.3    22  21.40   89.0   19.39  53.44  176.0
38  39  4.32   6.4  37.7  12.3    30  21.03   98.3   19.63  48.78  169.9
39  40  4.06   5.8  38.7  12.8    78  21.77  122.1   23.11  56.05  183.0
40  41  4.12   6.1  36.6  11.8    21  21.38   90.4   16.86  56.45  178.2
41  42  4.17   5.0  37.4  12.7   109  21.47  106.9   21.32  53.11  177.3
42  43  3.80   6.6  36.5  12.4   102  24.45  156.6   26.57  54.41  174.1
43  44  3.96   5.5  36.3  12.4    71  22.63  101.1   17.93  55.97  173.6
44  45  4.44   9.7  41.4  14.1    64  22.80  126.4   24.97  51.62  173.7
45  46  4.27  10.6  37.7  12.5    68  23.58  114.0   22.62  58.27  178.7
46  47  3.90   6.3  35.9  12.1    78  20.06   70.0   15.01  57.28  183.3
47  48  4.02   9.1  37.7  12.7   107  23.01   77.0   18.14  57.30  174.4
48  49  4.39   9.6  38.3  12.5    39  24.64  148.9   26.78  54.18  173.3
49  50  4.52   5.1  38.8  13.1    58  18.26   80.1   17.22  42.96  168.6
50  51  4.25  10.7  39.5  13.2   127  24.47  156.6   26.50  54.46  174.0
51  52  4.46  10.9  39.7  13.7   102  23.99  115.9   23.01  57.20  176.0
52  53  4.40   9.3  40.4  13.6    86  26.24  181.7   30.10  54.38  172.2
53  54  4.83   8.4  41.8  13.4    40  20.04   71.6   13.93  57.58  182.7
54  55  4.23   6.9  38.3  12.6    50  25.72  143.5   26.65  61.46  180.5
55  56  4.24   8.4  37.6  12.5    58  25.64  200.8   35.52  53.46  179.8
56  57  3.95   6.6  38.4  12.8    33  19.87   68.9   15.59  54.11  179.6
57  58  4.03   8.5  37.7  13.0    51  23.35  103.6   19.61  55.35  171.7

      wt sex    sport
35  59.9   f  Netball
36  63.0   f  Netball
37  66.3   f  Netball
38  60.7   f  Netball
39  72.9   f  Netball
40  67.9   f  Netball
41  67.5   f  Netball
42  74.1   f  Netball
43  68.2   f  Netball
44  68.8   f  Netball
45  75.3   f  Netball
46  67.4   f  Netball
47  70.0   f  Netball
48  74.0   f  Netball
49  51.9   f  Netball
50  74.1   f  Netball
51  74.3   f  Netball
52  77.8   f  Netball
53  66.9   f  Netball
54  83.8   f  Netball
55  82.9   f  Netball
56  64.1   f  Netball
57  68.8   f  Netball
35    59.9
36    63.0
37    66.3
38    60.7
39    72.9
40    67.9
41    67.5
42    74.1
43    68.2
44    68.8
45    75.3
46    67.4
47    70.0
48    74.0
49    51.9
50    74.1
51    74.3
52    77.8
53    66.9
54    83.8
55    82.9
56    64.1
57    68.8
Name: wt, dtype: float64
<StringArray>
['Netball', 'Field', 'Swim', 'Row', 'T_Sprnt', 'W_Polo']
Length: 6, dtype: str
sport
Field      12
W_Polo      3
Swim        2
Row         2
Netball     1
T_Sprnt     1
Name: count, dtype: int64