In [1]:
# Package imports
import numpy as np                                  # "Scientific computing"
import scipy.stats as stats                         # Statistical tests

import pandas as pd                                 # Dataframe
import matplotlib.pyplot as plt                     # Basic visualisation
from statsmodels.graphics.mosaicplot import mosaic  # Mosaic plot
import seaborn as sns                               # Advanced dataviz

## Question 1

The data frame below shows the evolution of the average duration of a first marriage in Belgium, since 2015 by type of marriage (male-female / female-female / male-male) (Source: StatBel). Can we say that a man-man marriage lasts significantly longer than a woman-woman marriage?  
Make a plot!

In [2]:
divorces = pd.DataFrame(data={
    'year': [2015,2016,2017,2018,2019,2020,2021,2022,2023],
    'm_f': [16.7, 16.9, 16.9, 16.7, 16.7, 16.4, 16.6, 16.7, 16.1],
    'f_f': [5.5, 6.4, 6.3, 7.4, 6.7, 6.7, 7.0, 7.8, 8.0],
    'm_m': [6.0, 6.3, 6.9, 7.4, 7.4, 8.0, 8.2, 8.2, 8.5]
}).set_index('year')
divorces.head()

       m_f  f_f  m_m
year
2015  16.7  5.5  6.0
2016  16.9  6.4  6.3
2017  16.9  6.3  6.9
2018  16.7  7.4  7.4
2019  16.7  6.7  7.4

## Question 2

The data frame below shows the evolution of the average duration of a first and a subsequent marriage in Belgium since 2015 (Source: StatBel). Can we say that a first marriage lasts significantly longer than a subsequent marriage? Make a plot!

In [4]:
divorces = pd.DataFrame(data={
    'year': [2015,2016,2017,2018,2019,2020,2021,2022,2023],
    'first_marriage': [16.7, 16.9, 16.9, 16.7, 16.7, 16.4, 16.6, 16.7, 16.1],
    'subsequent_marriage': [10.5, 11.0, 11.2, 11.3, 11.3, 11.4, 11.5, 11.9, 11.8]
}).set_index('year')
divorces.head()

      first_marriage  subsequent_marriage
year
2015            16.7                 10.5
2016            16.9                 11.0
2017            16.9                 11.2
2018            16.7                 11.3
2019            16.7                 11.3

## Question 3
A local pizzeria claims that they can deliver pizza faster than a local branch of a large chain. To verify this, you ordered pizza from both of them 10 times. Below are the times (in minutes) they took. Can the local pizzeria indeed deliver pizzas significantly faster than the big player? Make a plot.

In [5]:
dfpizzas = pd.DataFrame(data= {'local': [16.8, 11.7, 15.6, 16.7, 17.5, 18.1, 14.1, 21.8, 13.9, 20.8],
                               'chain': [22.0, 15.2, 18.7, 15.6, 20.8, 19.5, 17.0, 19.5, 16.5, 24.0]})
dfpizzas.head()

   local  chain
0   16.8   22.0
1   11.7   15.2
2   15.6   18.7
3   16.7   15.6
4   17.5   20.8